// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_W7J3iFa3Sk-jqflQ0bZhF1_C1pCdnsY',
    appId: '1:662664573348:web:731f848b707c922aa4d131',
    messagingSenderId: '662664573348',
    projectId: 'agridirect-nepal',
    authDomain: 'agridirect-nepal.firebaseapp.com',
    storageBucket: 'agridirect-nepal.firebasestorage.app',
    measurementId: 'G-EQ64HL4J55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABpuQigraQcMv5oju2GBfOgEPk2IXoxB8',
    appId: '1:662664573348:android:0429e226e32fc134a4d131',
    messagingSenderId: '662664573348',
    projectId: 'agridirect-nepal',
    storageBucket: 'agridirect-nepal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ZGak1v7VUqz0OHEnLfTUbIWlvrB-27Q',
    appId: '1:662664573348:ios:591c39565e29802ea4d131',
    messagingSenderId: '662664573348',
    projectId: 'agridirect-nepal',
    storageBucket: 'agridirect-nepal.firebasestorage.app',
    iosClientId: '662664573348-luo2n0kb87us5os7dasq810083q1rcqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmtechAgridirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ZGak1v7VUqz0OHEnLfTUbIWlvrB-27Q',
    appId: '1:662664573348:ios:591c39565e29802ea4d131',
    messagingSenderId: '662664573348',
    projectId: 'agridirect-nepal',
    storageBucket: 'agridirect-nepal.firebasestorage.app',
    iosClientId: '662664573348-luo2n0kb87us5os7dasq810083q1rcqk.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmtechAgridirect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_W7J3iFa3Sk-jqflQ0bZhF1_C1pCdnsY',
    appId: '1:662664573348:web:da52fef659de4253a4d131',
    messagingSenderId: '662664573348',
    projectId: 'agridirect-nepal',
    authDomain: 'agridirect-nepal.firebaseapp.com',
    storageBucket: 'agridirect-nepal.firebasestorage.app',
    measurementId: 'G-CB1TXPP6R2',
  );
}
