// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


class DefaultFirebaseOptions
{
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAioavGNsG2CgnNq2O4tbfUNZ7B8tzOBFs',
    appId: '1:931317017971:web:b6266933117f06f8816906',
    messagingSenderId: '931317017971',
    projectId: 'agridirect-nepal-9fecd',
    authDomain: 'agridirect-nepal-9fecd.firebaseapp.com',
    storageBucket: 'agridirect-nepal-9fecd.firebasestorage.app',
    measurementId: 'G-NKZRMFXCY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5LYXahPufsCGJwhReMKQ_qkwiOSYsRi0',
    appId: '1:931317017971:android:fd1517137fa36761816906',
    messagingSenderId: '931317017971',
    projectId: 'agridirect-nepal-9fecd',
    storageBucket: 'agridirect-nepal-9fecd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxLLWgnhJqpUrKU0pD9ClvJvxeJ9O-3CQ',
    appId: '1:931317017971:ios:0bc4e90273dd28ef816906',
    messagingSenderId: '931317017971',
    projectId: 'agridirect-nepal-9fecd',
    storageBucket: 'agridirect-nepal-9fecd.firebasestorage.app',
    iosBundleId: 'com.example.farmtechAgridirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxLLWgnhJqpUrKU0pD9ClvJvxeJ9O-3CQ',
    appId: '1:931317017971:ios:0bc4e90273dd28ef816906',
    messagingSenderId: '931317017971',
    projectId: 'agridirect-nepal-9fecd',
    storageBucket: 'agridirect-nepal-9fecd.firebasestorage.app',
    iosBundleId: 'com.example.farmtechAgridirect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAioavGNsG2CgnNq2O4tbfUNZ7B8tzOBFs',
    appId: '1:931317017971:web:2445e6084b90c5ff816906',
    messagingSenderId: '931317017971',
    projectId: 'agridirect-nepal-9fecd',
    authDomain: 'agridirect-nepal-9fecd.firebaseapp.com',
    storageBucket: 'agridirect-nepal-9fecd.firebasestorage.app',
    measurementId: 'G-QKQFFL2B6Q',
  );

}