// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs7Bbsfe-ZCBb7pU8Kz-TDYo_KNbrQRXE',
    appId: '1:705986132915:web:cc65b98609ef3b251529c6',
    messagingSenderId: '705986132915',
    projectId: 'agridirectnepal',
    authDomain: 'agridirectnepal.firebaseapp.com',
    storageBucket: 'agridirectnepal.firebasestorage.app',
    measurementId: 'G-DZRVXZ33W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk7QdUh-nRP9Q5hhy9gbAUuKXEWMzRmg0',
    appId: '1:705986132915:android:283879a4d00157411529c6',
    messagingSenderId: '705986132915',
    projectId: 'agridirectnepal',
    storageBucket: 'agridirectnepal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3Hkrf8-1SPVaRLG-2TFalfLCVQEpEHM4',
    appId: '1:705986132915:ios:60ba64377f16d9931529c6',
    messagingSenderId: '705986132915',
    projectId: 'agridirectnepal',
    storageBucket: 'agridirectnepal.firebasestorage.app',
    iosClientId: '705986132915-80oeri43eqj3meb2burvpkeffsnqdrbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmtechAgridirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3Hkrf8-1SPVaRLG-2TFalfLCVQEpEHM4',
    appId: '1:705986132915:ios:60ba64377f16d9931529c6',
    messagingSenderId: '705986132915',
    projectId: 'agridirectnepal',
    storageBucket: 'agridirectnepal.firebasestorage.app',
    iosClientId: '705986132915-80oeri43eqj3meb2burvpkeffsnqdrbp.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmtechAgridirect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs7Bbsfe-ZCBb7pU8Kz-TDYo_KNbrQRXE',
    appId: '1:705986132915:web:ce68dd5aa5d8cddf1529c6',
    messagingSenderId: '705986132915',
    projectId: 'agridirectnepal',
    authDomain: 'agridirectnepal.firebaseapp.com',
    storageBucket: 'agridirectnepal.firebasestorage.app',
    measurementId: 'G-L0J3D776LY',
  );

}