import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

/// Seeds the database with Nepal products and categories.
/// Returns a map with success and error counts.
Future<Map<String, int>> seedProducts({List<String>? selectedCategories, List<String>? selectedSeasons, List<String>? selectedProductNames}) async {
  int productSuccess = 0;
  int productError = 0;
  int categorySuccess = 0;
  int categoryError = 0;

  final User? user = FirebaseAuth.instance.currentUser;
  if (user == null) throw Exception("Authentication required for seeding.");

  final List<Map<String, dynamic>> nepalProducts = [
    // --- VEGETABLES ---
    {
      "title": "Local Adhuwa (Ginger)",
      "name": "Local Adhuwa (Ginger)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 140,
      "unit": "kg",
      "description": "Organic fresh ginger with strong aroma from Palpa.",
      "longDescription": "High-quality fresh ginger roots, known for their strong aroma and medicinal properties. Essential for Nepali tea and traditional curries.",
      "image": "https://cdn-icons-png.flaticon.com/512/3944/3944111.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/3944/3944111.png",
      "farmName": "Palpa Ginger Hub",
      "badge": "Organic",
      "badgeColor": 0xFF2E7D32,
    },
    {
      "title": "Mude ko Aloo",
      "name": "Mude ko Aloo",
      "category": "Vegetables",
      "season": "All Year",
      "price": 85,
      "unit": "kg",
      "description": "Famous red potatoes from high altitudes of Mude.",
      "longDescription": "These red potatoes are grown in the high altitudes of Sindhupalchowk. They are famous for their unique texture and rich taste.",
      "image": "https://cdn-icons-png.flaticon.com/512/5769/5769435.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5769/5769435.png",
      "farmName": "Mude Highland Cooperatives",
      "badge": "Premium",
      "badgeColor": 0xFFF57C00,
    },
    {
      "title": "Local Golbheda (Tomato)",
      "name": "Local Golbheda (Tomato)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 60,
      "unit": "kg",
      "description": "Fresh, vine-ripened organic tomatoes.",
      "longDescription": "Juicy and plump tomatoes grown in local polytunnels without harmful pesticides. Perfect for salads and tangy Nepali chutneys.",
      "image": "https://cdn-icons-png.flaticon.com/512/1202/1202125.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1202/1202125.png",
      "farmName": "Kathmandu Valley Green Farms",
      "badge": "Fresh",
      "badgeColor": 0xFFD32F2F,
    },
    {
      "title": "Local Kauli (Cauliflower)",
      "name": "Local Kauli (Cauliflower)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 70,
      "unit": "kg",
      "description": "Crispy white cauliflower from Palung valley.",
      "longDescription": "Palung is famous for its high-altitude cauliflower. These are sweeter and crunchier than plain varieties.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029194.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029194.png",
      "farmName": "Mountain Fresh Palung",
      "badge": "Seasonal",
      "badgeColor": 0xFF1976D2,
    },
    {
      "title": "Ramtoriya (Okra)",
      "name": "Ramtoriya (Okra)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 90,
      "unit": "kg",
      "description": "Tender green lady fingers from the Terai plains.",
      "longDescription": "Freshly picked okra, rich in fiber and minerals. Best enjoyed as a crispy fry or in gravy.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329868.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329868.png",
      "farmName": "Chitwan Agri Hub",
      "badge": "Tender",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Tite Karela (Bitter Gourd)",
      "name": "Tite Karela (Bitter Gourd)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 80,
      "unit": "kg",
      "description": "Organic bitter gourd with high medicinal value.",
      "longDescription": "Known for controlling blood sugar, our bitter gourds are grown traditionally in the Terai region.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329863.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329863.png",
      "farmName": "Bara Organic Village",
      "badge": "Healthy",
      "badgeColor": 0xFF388E3C,
    },
    {
      "title": "Lauka (Bottle Gourd)",
      "name": "Lauka (Bottle Gourd)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 45,
      "unit": "kg",
      "description": "Fresh and light bottle gourd.",
      "longDescription": "Easy to digest and hydrating, these bottle gourds are perfect for a light summer meal.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329871.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329871.png",
      "farmName": "Terai Greens",
      "badge": "Light",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Local Mula (Radish)",
      "name": "Local Mula (Radish)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 40,
      "unit": "kg",
      "description": "Crispy white radish for pickles and salads.",
      "longDescription": "Fresh winter radish, perfect for making traditional sun-dried 'Sinki' or fresh spicy pickles.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329851.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329851.png",
      "farmName": "Bhaktapur Roots",
      "badge": "Crunchy",
      "badgeColor": 0xFF00BCD4,
    },
    {
      "title": "Local Bandakopi (Cabbage)",
      "name": "Local Bandakopi (Cabbage)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 55,
      "unit": "kg",
      "description": "Fresh and compact green cabbage.",
      "longDescription": "Directly from the farm, these cabbages are sweet and packed with nutrients. Great for stir-fry and momo fillings.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329845.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329845.png",
      "farmName": "Lalitpur Agro Farm",
      "badge": "Eco-Friendly",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Pharsi (Pumpkin)",
      "name": "Pharsi (Pumpkin)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 45,
      "unit": "kg",
      "description": "Sweet local pumpkin rich in Vitamin A.",
      "longDescription": "Large, ripe pumpkins from the plains of Nepal. Perfect for soups, curries, and traditional desserts.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329875.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329875.png",
      "farmName": "Terai Harvest",
      "badge": "Sweet",
      "badgeColor": 0xFFFF9800,
    },
    {
      "title": "Palungo ko Saag (Spinach)",
      "name": "Palungo ko Saag (Spinach)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 50,
      "unit": "bundle",
      "description": "Iron-rich fresh spinach leaves.",
      "longDescription": "Freshly harvested organic spinach from the valley. Packed with iron and essential vitamins.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329853.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329853.png",
      "farmName": "Valley Greens",
      "badge": "Superfood",
      "badgeColor": 0xFF43A047,
    },
    {
      "title": "Kakro (Cucumber)",
      "name": "Kakro (Cucumber)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 65,
      "unit": "kg",
      "description": "Hydrating local cucumbers from Bhaktapur.",
      "longDescription": "Crispy and refreshing cucumbers. Perfect for summer salads and traditional Nepali pickles.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329846.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329846.png",
      "farmName": "Bhaktapur Vegetable Group",
      "badge": "Hydrating",
      "badgeColor": 0xFF009688,
    },
    {
      "title": "Bhanta (Eggplant)",
      "name": "Bhanta (Eggplant)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 75,
      "unit": "kg",
      "description": "Shiny purple local brinjals.",
      "longDescription": "Tender and meaty eggplants, ideal for roasting or making traditional 'Bhanta ko Achar'.",
      "image": "https://cdn-icons-png.flaticon.com/512/1147/1147820.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1147/1147820.png",
      "farmName": "Parsa Agri Farms",
      "badge": "Fresh",
      "badgeColor": 0xFF673AB7,
    },
    {
      "title": "Gajar (Carrot)",
      "name": "Gajar (Carrot)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 80,
      "unit": "kg",
      "description": "Sweet and crunchy organic carrots.",
      "longDescription": "Grown in the loose soil of the valley, these carrots are extremely sweet and perfect for juice or raw consumption.",
      "image": "https://cdn-icons-png.flaticon.com/512/1147/1147833.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1147/1147833.png",
      "farmName": "Green Valley Organic",
      "badge": "Organic",
      "badgeColor": 0xFFFF5722,
    },
    {
      "title": "Local Lehsun (Garlic)",
      "name": "Local Lehsun (Garlic)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 350,
      "unit": "kg",
      "description": "Strongly flavored local Nepali garlic.",
      "longDescription": "Small-cloved but intensely flavored garlic grown in the mid-hills. Superior to imported varieties in medicinal value.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329849.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329849.png",
      "farmName": "Hillside Spice Coop",
      "badge": "Intense",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Kurilo (Asparagus)",
      "name": "Kurilo (Asparagus)",
      "category": "Vegetables",
      "season": "Spring",
      "price": 450,
      "unit": "kg",
      "description": "Wild and nutritious Himalayan asparagus.",
      "longDescription": "Freshly foraged and cultivated asparagus, known for its high nutrient density and delicate flavor.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029202.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029202.png",
      "farmName": "Mountain Wild Harvest",
      "badge": "Rare",
      "badgeColor": 0xFF00796B,
    },
    {
      "title": "Dhaniya (Coriander)",
      "name": "Dhaniya (Coriander)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 20,
      "unit": "bunch",
      "description": "Fresh and aromatic coriander leaves.",
      "longDescription": "Essential garnish for every Nepali dish. Our coriander is grown without harmful chemical fertilizers.",
      "image": "https://cdn-icons-png.flaticon.com/512/1135/1135502.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1135/1135502.png",
      "farmName": "Local Garden Coop",
      "badge": "Aromatic",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Matar Kosha (Peas)",
      "name": "Matar Kosha (Peas)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 120,
      "unit": "kg",
      "description": "Sweet and tender local green peas.",
      "longDescription": "Freshly shelled or in pod, these winter peas are a seasonal favorite in the Kathmandu valley.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329858.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329858.png",
      "farmName": "Valley Winter Farms",
      "badge": "Seasonal",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Ghiu Simi (French Beans)",
      "name": "Ghiu Simi (French Beans)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 85,
      "unit": "kg",
      "description": "Tender and stringless French beans.",
      "longDescription": "Crispy green beans grown in the mid-hills, perfect for stir-fry or tarkari.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029205.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029205.png",
      "farmName": "Hilly Harvest",
      "badge": "Fresh",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Akabare Khursani (Green Chili)",
      "name": "Akabare Khursani (Green Chili)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 150,
      "unit": "250g",
      "description": "Spicy and aromatic local chilies.",
      "longDescription": "Intensely hot and aromatic chilies from Eastern Nepal. A must-have for spice lovers.",
      "image": "https://cdn-icons-png.flaticon.com/512/1147/1147823.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1147/1147823.png",
      "farmName": "Eastern Spices",
      "badge": "Hot",
      "badgeColor": 0xFFF44336,
    },

    // --- FRUITS ---
    {
      "title": "Mustang Apple",
      "name": "Mustang Apple",
      "category": "Fruits",
      "season": "Autumn",
      "price": 260,
      "unit": "kg",
      "description": "Crispy organic apples from the high Himalayas.",
      "longDescription": "Grown in Marpha, Mustang. These apples are famous for their unique sweetness and crunch due to the mountain climate.",
      "image": "https://cdn-icons-png.flaticon.com/512/415/415733.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/415/415733.png",
      "farmName": "Marpha Himalayan Orchard",
      "badge": "Himalayan",
      "badgeColor": 0xFF7B1FA2,
    },
    {
      "title": "Nepali Suntala (Orange)",
      "name": "Nepali Suntala (Orange)",
      "category": "Fruits",
      "season": "Winter",
      "price": 160,
      "unit": "kg",
      "description": "Juicy and sweet oranges from the hills of Gulmi.",
      "longDescription": "Gulmi oranges are known for their thin skin and high juice content. 100% natural and tree-ripened.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329891.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329891.png",
      "farmName": "Gulmi Citrus Grove",
      "badge": "Sweet",
      "badgeColor": 0xFFFFA000,
    },
    {
      "title": "Terai Malda Mango",
      "name": "Terai Malda Mango",
      "category": "Fruits",
      "season": "Summer",
      "price": 220,
      "unit": "kg",
      "description": "The king of mangoes from Saptari.",
      "longDescription": "Premium Malda mangoes, known for their fiber-less pulp and divine sweetness. Chemical-free ripening.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029227.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029227.png",
      "farmName": "Saptari Tropical Fruit",
      "badge": "Premium",
      "badgeColor": 0xFFFFD600,
    },
    {
      "title": "Local Banana (Kera)",
      "name": "Local Banana (Kera)",
      "category": "Fruits",
      "season": "All Year",
      "price": 120,
      "unit": "dozen",
      "description": "Sweet local 'Malbhog' bananas.",
      "longDescription": "Small but extremely sweet and aromatic local bananas grown in the Terai and mid-hills.",
      "image": "https://cdn-icons-png.flaticon.com/512/415/415737.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/415/415737.png",
      "farmName": "Kavre Banana Farm",
      "badge": "Aromatic",
      "badgeColor": 0xFFFBC02D,
    },
    {
      "title": "Mewabi (Papaya)",
      "name": "Mewabi (Papaya)",
      "category": "Fruits",
      "season": "All Year",
      "price": 90,
      "unit": "kg",
      "description": "Sun-ripened sweet papaya from the plains.",
      "longDescription": "Rich in digestive enzymes and vitamins. Our papayas are naturally ripened on the tree.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029231.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029231.png",
      "farmName": "Chitwan Fruit Estate",
      "badge": "Digestive Aid",
      "badgeColor": 0xFFFFC107,
    },
    {
      "title": "Amala (Gooseberry)",
      "name": "Amala (Gooseberry)",
      "category": "Fruits",
      "season": "Winter",
      "price": 140,
      "unit": "kg",
      "description": "Wild Himalayan gooseberries with high Vitamin C.",
      "longDescription": "Collected from community forests, these gooseberries are powerful immunity boosters used in traditional medicine.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029217.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029217.png",
      "farmName": "Himalayan Herbs",
      "badge": "Immunity",
      "badgeColor": 0xFF009688,
    },
    {
      "title": "Local Grapes (Angur)",
      "name": "Local Grapes (Angur)",
      "category": "Fruits",
      "season": "Summer",
      "price": 350,
      "unit": "kg",
      "description": "Sweet and juicy local green grapes.",
      "longDescription": "Fresh table grapes grown in the foothills of Nepal. Sweet with a slight refreshing tang.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329898.png",
      "imageUrl": "https://png.pngtree.com/png-vector/20241225/ourmid/pngtree-delicious-black-grapes-png-image_14877346.png",
      "farmName": "Nawalpur Vineyard",
      "badge": "Fresh",
      "badgeColor": 0xFF9C27B0,
    },
    {
      "title": "Bhuikatar (Pineapple)",
      "name": "Bhuikatar (Pineapple)",
      "category": "Fruits",
      "season": "Summer",
      "price": 150,
      "unit": "piece",
      "description": "Tangy and sweet pineapples from the Terai.",
      "longDescription": "Juicy pineapples harvested at peak ripeness. A tropical delight from the gardens of Eastern Nepal.",
      "image": "https://cdn-icons-png.flaticon.com/512/415/415764.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/415/415764.png",
      "farmName": "Eastern Fruit Hub",
      "badge": "Juicy",
      "badgeColor": 0xFFCDDC39,
    },
    {
      "title": "Anar (Pomegranate)",
      "name": "Anar (Pomegranate)",
      "category": "Fruits",
      "season": "All Year",
      "price": 380,
      "unit": "kg",
      "description": "Red and juicy pomegranate seeds.",
      "longDescription": "Highly nutritious pomegranates, known for blood-building properties. Sweet with deep red arils.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029232.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029232.png",
      "farmName": "Salyan Pomegranate Farm",
      "badge": "Healthy",
      "badgeColor": 0xFFE91E63,
    },
    {
      "title": "Amba (Guava)",
      "name": "Amba (Guava)",
      "category": "Fruits",
      "season": "Autumn",
      "price": 80,
      "unit": "kg",
      "description": "Sweet and fragrant local guavas.",
      "longDescription": "White-fleshed local guavas, crunchy and sweet. Harvested directly from the orchards of the mid-hills.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029221.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029221.png",
      "farmName": "Mid-Hill Orchards",
      "badge": "Fragrant",
      "badgeColor": 0xFF4CAF50,
    },

    // --- DAIRY ---
    {
      "title": "Fresh Buffalo Milk",
      "name": "Fresh Buffalo Milk",
      "category": "Dairy",
      "season": "All Year",
      "price": 110,
      "unit": "liter",
      "description": "Pure, unadulterated fresh buffalo milk.",
      "longDescription": "Rich and creamy buffalo milk collected daily from local farmers. No preservatives or chemicals added.",
      "image": "https://cdn-icons-png.flaticon.com/512/372/372971.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/372/372971.png",
      "farmName": "Lalitpur Dairy Farmers",
      "badge": "Pure",
      "badgeColor": 0xFF1976D2,
    },
    {
      "title": "Local Dahi (Curd)",
      "name": "Local Dahi (Curd)",
      "category": "Dairy",
      "season": "All Year",
      "price": 180,
      "unit": "liter",
      "description": "Traditional thick and creamy local curd.",
      "longDescription": "Made from pure buffalo milk using traditional methods. Thick, creamy, and naturally probiotic.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329906.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329906.png",
      "farmName": "Bhaktapur Dairy",
      "badge": "Traditional",
      "badgeColor": 0xFF2196F3,
    },
    {
      "title": "Local Ghiu (Ghee)",
      "name": "Local Ghiu (Ghee)",
      "category": "Dairy",
      "season": "All Year",
      "price": 1400,
      "unit": "kg",
      "description": "Pure hand-churned buffalo ghee.",
      "longDescription": "Traditionally churned using 'Theki-Madan'. Rich aroma and granular texture. Highly nutritious healthy fat.",
      "image": "https://cdn-icons-png.flaticon.com/512/1218/1218698.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1218/1218698.png",
      "farmName": "Village Dairy Coop",
      "badge": "Pure",
      "badgeColor": 0xFFFFC107,
    },
    {
      "title": "Fresh Paneer",
      "name": "Fresh Paneer",
      "category": "Dairy",
      "season": "All Year",
      "price": 850,
      "unit": "kg",
      "description": "Soft and fresh buffalo milk cottage cheese.",
      "longDescription": "Made daily from fresh whole milk. Soft, spongy, and perfect for all your gourmet recipes.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029252.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029252.png",
      "farmName": "Valley Dairy",
      "badge": "High Protein",
      "badgeColor": 0xFF3F51B5,
    },
    {
      "title": "Nauyani (Fresh Butter)",
      "name": "Nauyani (Fresh Butter)",
      "category": "Dairy",
      "season": "All Year",
      "price": 1100,
      "unit": "kg",
      "description": "Traditional white butter from buffalo milk.",
      "longDescription": "Pure and fresh white butter, hand-churned in the village. Perfect for spreading on warm rotis.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029248.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029248.png",
      "farmName": "Hillside Dairy",
      "badge": "Handmade",
      "badgeColor": 0xFF8D6E63,
    },

    // --- GRAINS ---
    {
      "title": "Jumli Marshi Rice",
      "name": "Jumli Marshi Rice",
      "category": "Grains",
      "season": "All Year",
      "price": 320,
      "unit": "kg",
      "description": "Indigenous red rice from high-altitude Jumla.",
      "longDescription": "Cold-resistant indigenous red rice. Extremely nutritious and prized for its unique flavor and health benefits.",
      "image": "https://cdn-icons-png.flaticon.com/512/1000/1000145.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1000/1000145.png",
      "farmName": "Karnali Highland Grains",
      "badge": "Superfood",
      "badgeColor": 0xFF8D6E63,
    },
    {
      "title": "Local Kodo (Millet)",
      "name": "Local Kodo (Millet)",
      "category": "Grains",
      "season": "All Year",
      "price": 110,
      "unit": "kg",
      "description": "Stone-ground nutritious finger millet.",
      "longDescription": "High-fiber millet from the hills of Kavre. Essential for making traditional and healthy 'Dhido'.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029272.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029272.png",
      "farmName": "Kavre Hill Farming",
      "badge": "Healthy",
      "badgeColor": 0xFF6D4C41,
    },
    {
      "title": "Local Gahun (Wheat)",
      "name": "Local Gahun (Wheat)",
      "category": "Grains",
      "season": "All Year",
      "price": 95,
      "unit": "kg",
      "description": "Whole wheat grains from local fields.",
      "longDescription": "Stone-milled wheat grains, rich in bran and nutrients. Perfect for traditional rotis.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329918.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329918.png",
      "farmName": "Terai Wheat Belt",
      "badge": "Whole Grain",
      "badgeColor": 0xFFF44336,
    },
    {
      "title": "Local Makai (Maize)",
      "name": "Local Makai (Maize)",
      "category": "Grains",
      "season": "All Year",
      "price": 85,
      "unit": "kg",
      "description": "Sun-dried local yellow maize.",
      "longDescription": "Traditionally grown yellow corn, perfect for popping or making cornmeal (Chamre).",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329915.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329915.png",
      "farmName": "Hillside Corn Farms",
      "badge": "Natural",
      "badgeColor": 0xFFFFEB3B,
    },
    {
      "title": "Nepali Quinoa",
      "name": "Nepali Quinoa",
      "category": "Grains",
      "season": "All Year",
      "price": 450,
      "unit": "kg",
      "description": "Locally grown high-protein quinoa.",
      "longDescription": "A modern addition to Nepali agriculture, quinoa is a complete protein source grown in the mountains.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029279.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029279.png",
      "farmName": "Mustang Supergrains",
      "badge": "Protein Rich",
      "badgeColor": 0xFF009688,
    },
    {
      "title": "Makai (Sweet Corn)",
      "name": "Makai (Sweet Corn)",
      "category": "Grains",
      "season": "Summer",
      "price": 60,
      "unit": "piece",
      "description": "Sweet and tender American corn grown locally.",
      "longDescription": "Juicy and sweet yellow corn, perfect for roasting or boiling during the summer monsoon.",
      "image": "https://cdn-icons-png.flaticon.com/512/415/415758.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/415/415758.png",
      "farmName": "Valley Corn Hub",
      "badge": "Sweet",
      "badgeColor": 0xFFFFC107,
    },

    // --- PULSES & SPICES ---
    {
      "title": "Bhatmas (Soybean)",
      "name": "Bhatmas (Soybean)",
      "category": "Pulses",
      "season": "All Year",
      "price": 180,
      "unit": "kg",
      "description": "High-protein local soybeans.",
      "longDescription": "Yellow soybeans from the mid-hills. Perfect for roasting and making 'Bhatmas Sadeko'.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029288.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029288.png",
      "farmName": "Local Pulse Coop",
      "badge": "Protein",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Beshar (Turmeric)",
      "name": "Beshar (Turmeric)",
      "category": "Spices",
      "season": "All Year",
      "price": 180,
      "unit": "250g",
      "description": "Pure organic turmeric powder from Salyan.",
      "longDescription": "Grown in the fertile soil of Salyan, this turmeric has exceptionally high curcumin content and deep color.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329860.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329860.png",
      "farmName": "Salyan Organic Village",
      "badge": "High Curcumin",
      "badgeColor": 0xFFFF6F00,
    },
    {
      "title": "Himalayan Honey",
      "name": "Himalayan Honey",
      "category": "Specialty",
      "season": "All Year",
      "price": 1200,
      "unit": "kg",
      "description": "Raw, wild honey from the cliffs of Mustang.",
      "longDescription": "Raw and unprocessed honey collected by honey hunters. Rich in medicinal properties and distinct mountain floral notes.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329924.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329924.png",
      "farmName": "Mustang Bee Hunters",
      "badge": "Wild Raw",
      "badgeColor": 0xFFFBC02D,
    },
  ];

  final CollectionReference products = FirebaseFirestore.instance.collection('master_catalog');

  for (var product in nepalProducts) {
    bool nameMatch = selectedProductNames == null || selectedProductNames.contains(product['name']);
    bool catMatch = selectedCategories == null || selectedCategories.contains(product['category']);
    bool seasonMatch = selectedSeasons == null || selectedSeasons.contains(product['season']) || product['season'] == 'All Year';

    if (nameMatch && (selectedProductNames != null || (catMatch && seasonMatch))) {
      try {
        product['addedAt'] = FieldValue.serverTimestamp();
        product['updatedAt'] = FieldValue.serverTimestamp();
        product['rating'] = 4.8;
        product['status'] = 'approved';
        
        String docId = product['name'].toString().replaceAll(' ', '_').toLowerCase();
        
        await products.doc(docId).set(product, SetOptions(merge: true)).timeout(
          const Duration(seconds: 10),
          onTimeout: () => throw Exception("Write timeout for ${product['name']}"),
        );

        Map<String, dynamic> liveProduct = Map.from(product);
        liveProduct['isSample'] = true;
        await FirebaseFirestore.instance.collection('products').doc(docId).set(liveProduct, SetOptions(merge: true));
        
        productSuccess++;
      } catch (e) {
        productError++;
      }
    }
  }

  // Categories seed
  final List<Map<String, dynamic>> categoriesData = [
    {"name": "Vegetables", "iconCode": Icons.eco_outlined.codePoint},
    {"name": "Fruits", "iconCode": Icons.apple_outlined.codePoint},
    {"name": "Dairy", "iconCode": Icons.local_drink_outlined.codePoint},
    {"name": "Grains", "iconCode": Icons.grain.codePoint},
    {"name": "Tea & Coffee", "iconCode": Icons.local_cafe_outlined.codePoint},
    {"name": "Spices", "iconCode": Icons.flare.codePoint},
    {"name": "Pulses", "iconCode": Icons.lens_blur.codePoint},
    {"name": "Mushrooms", "iconCode": Icons.spa.codePoint},
    {"name": "Specialty", "iconCode": Icons.star_border.codePoint},
  ];

  final CollectionReference categoriesCol = FirebaseFirestore.instance.collection('categories');
  for (var cat in categoriesData) {
    try {
      await categoriesCol.doc(cat['name']).set(cat, SetOptions(merge: true));
      categorySuccess++;
    } catch (e) {
      categoryError++;
    }
  }
  
  return {
    'productSuccess': productSuccess,
    'productError': productError,
    'categorySuccess': categorySuccess,
    'categoryError': categoryError,
  };
}

final List<Map<String, dynamic>> nepalProductsList = [
    // --- VEGETABLES ---
    {
      "title": "Local Adhuwa (Ginger)",
      "name": "Local Adhuwa (Ginger)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 140,
      "unit": "kg",
      "description": "Organic fresh ginger with strong aroma from Palpa.",
      "longDescription": "High-quality fresh ginger roots, known for their strong aroma and medicinal properties. Essential for Nepali tea and traditional curries.",
      "image": "https://cdn-icons-png.flaticon.com/512/3944/3944111.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/3944/3944111.png",
      "farmName": "Palpa Ginger Hub",
      "badge": "Organic",
      "badgeColor": 0xFF2E7D32,
    },
    {
      "title": "Mude ko Aloo",
      "name": "Mude ko Aloo",
      "category": "Vegetables",
      "season": "All Year",
      "price": 85,
      "unit": "kg",
      "description": "Famous red potatoes from high altitudes of Mude.",
      "longDescription": "These red potatoes are grown in the high altitudes of Sindhupalchowk. They are famous for their unique texture and rich taste.",
      "image": "https://cdn-icons-png.flaticon.com/512/5769/5769435.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5769/5769435.png",
      "farmName": "Mude Highland Cooperatives",
      "badge": "Premium",
      "badgeColor": 0xFFF57C00,
    },
    {
      "title": "Local Golbheda (Tomato)",
      "name": "Local Golbheda (Tomato)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 60,
      "unit": "kg",
      "description": "Fresh, vine-ripened organic tomatoes.",
      "longDescription": "Juicy and plump tomatoes grown in local polytunnels without harmful pesticides. Perfect for salads and tangy Nepali chutneys.",
      "image": "https://cdn-icons-png.flaticon.com/512/1202/1202125.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1202/1202125.png",
      "farmName": "Kathmandu Valley Green Farms",
      "badge": "Fresh",
      "badgeColor": 0xFFD32F2F,
    },
    {
      "title": "Local Kauli (Cauliflower)",
      "name": "Local Kauli (Cauliflower)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 70,
      "unit": "kg",
      "description": "Crispy white cauliflower from Palung valley.",
      "longDescription": "Palung is famous for its high-altitude cauliflower. These are sweeter and crunchier than plain varieties.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029194.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029194.png",
      "farmName": "Mountain Fresh Palung",
      "badge": "Seasonal",
      "badgeColor": 0xFF1976D2,
    },
    {
      "title": "Ramtoriya (Okra)",
      "name": "Ramtoriya (Okra)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 90,
      "unit": "kg",
      "description": "Tender green lady fingers from the Terai plains.",
      "longDescription": "Freshly picked okra, rich in fiber and minerals. Best enjoyed as a crispy fry or in gravy.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329868.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329868.png",
      "farmName": "Chitwan Agri Hub",
      "badge": "Tender",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Tite Karela (Bitter Gourd)",
      "name": "Tite Karela (Bitter Gourd)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 80,
      "unit": "kg",
      "description": "Organic bitter gourd with high medicinal value.",
      "longDescription": "Known for controlling blood sugar, our bitter gourds are grown traditionally in the Terai region.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329863.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329863.png",
      "farmName": "Bara Organic Village",
      "badge": "Healthy",
      "badgeColor": 0xFF388E3C,
    },
    {
      "title": "Lauka (Bottle Gourd)",
      "name": "Lauka (Bottle Gourd)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 45,
      "unit": "kg",
      "description": "Fresh and light bottle gourd.",
      "longDescription": "Easy to digest and hydrating, these bottle gourds are perfect for a light summer meal.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329871.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329871.png",
      "farmName": "Terai Greens",
      "badge": "Light",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Local Mula (Radish)",
      "name": "Local Mula (Radish)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 40,
      "unit": "kg",
      "description": "Crispy white radish for pickles and salads.",
      "longDescription": "Fresh winter radish, perfect for making traditional sun-dried 'Sinki' or fresh spicy pickles.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329851.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329851.png",
      "farmName": "Bhaktapur Roots",
      "badge": "Crunchy",
      "badgeColor": 0xFF00BCD4,
    },
    {
      "title": "Local Bandakopi (Cabbage)",
      "name": "Local Bandakopi (Cabbage)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 55,
      "unit": "kg",
      "description": "Fresh and compact green cabbage.",
      "longDescription": "Directly from the farm, these cabbages are sweet and packed with nutrients. Great for stir-fry and momo fillings.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329845.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329845.png",
      "farmName": "Lalitpur Agro Farm",
      "badge": "Eco-Friendly",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Pharsi (Pumpkin)",
      "name": "Pharsi (Pumpkin)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 45,
      "unit": "kg",
      "description": "Sweet local pumpkin rich in Vitamin A.",
      "longDescription": "Large, ripe pumpkins from the plains of Nepal. Perfect for soups, curries, and traditional desserts.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329875.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329875.png",
      "farmName": "Terai Harvest",
      "badge": "Sweet",
      "badgeColor": 0xFFFF9800,
    },
    {
      "title": "Palungo ko Saag (Spinach)",
      "name": "Palungo ko Saag (Spinach)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 50,
      "unit": "bundle",
      "description": "Iron-rich fresh spinach leaves.",
      "longDescription": "Freshly harvested organic spinach from the valley. Packed with iron and essential vitamins.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329853.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329853.png",
      "farmName": "Valley Greens",
      "badge": "Superfood",
      "badgeColor": 0xFF43A047,
    },
    {
      "title": "Kakro (Cucumber)",
      "name": "Kakro (Cucumber)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 65,
      "unit": "kg",
      "description": "Hydrating local cucumbers from Bhaktapur.",
      "longDescription": "Crispy and refreshing cucumbers. Perfect for summer salads and traditional Nepali pickles.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329846.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329846.png",
      "farmName": "Bhaktapur Vegetable Group",
      "badge": "Hydrating",
      "badgeColor": 0xFF009688,
    },
    {
      "title": "Bhanta (Eggplant)",
      "name": "Bhanta (Eggplant)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 75,
      "unit": "kg",
      "description": "Shiny purple local brinjals.",
      "longDescription": "Tender and meaty eggplants, ideal for roasting or making traditional 'Bhanta ko Achar'.",
      "image": "https://cdn-icons-png.flaticon.com/512/1147/1147820.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1147/1147820.png",
      "farmName": "Parsa Agri Farms",
      "badge": "Fresh",
      "badgeColor": 0xFF673AB7,
    },
    {
      "title": "Gajar (Carrot)",
      "name": "Gajar (Carrot)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 80,
      "unit": "kg",
      "description": "Sweet and crunchy organic carrots.",
      "longDescription": "Grown in the loose soil of the valley, these carrots are extremely sweet and perfect for juice or raw consumption.",
      "image": "https://cdn-icons-png.flaticon.com/512/1147/1147833.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1147/1147833.png",
      "farmName": "Green Valley Organic",
      "badge": "Organic",
      "badgeColor": 0xFFFF5722,
    },
    {
      "title": "Local Lehsun (Garlic)",
      "name": "Local Lehsun (Garlic)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 350,
      "unit": "kg",
      "description": "Strongly flavored local Nepali garlic.",
      "longDescription": "Small-cloved but intensely flavored garlic grown in the mid-hills. Superior to imported varieties in medicinal value.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329849.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329849.png",
      "farmName": "Hillside Spice Coop",
      "badge": "Intense",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Kurilo (Asparagus)",
      "name": "Kurilo (Asparagus)",
      "category": "Vegetables",
      "season": "Spring",
      "price": 450,
      "unit": "kg",
      "description": "Wild and nutritious Himalayan asparagus.",
      "longDescription": "Freshly foraged and cultivated asparagus, known for its high nutrient density and delicate flavor.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029202.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029202.png",
      "farmName": "Mountain Wild Harvest",
      "badge": "Rare",
      "badgeColor": 0xFF00796B,
    },
    {
      "title": "Dhaniya (Coriander)",
      "name": "Dhaniya (Coriander)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 20,
      "unit": "bunch",
      "description": "Fresh and aromatic coriander leaves.",
      "longDescription": "Essential garnish for every Nepali dish. Our coriander is grown without harmful chemical fertilizers.",
      "image": "https://cdn-icons-png.flaticon.com/512/1135/1135502.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1135/1135502.png",
      "farmName": "Local Garden Coop",
      "badge": "Aromatic",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Matar Kosha (Peas)",
      "name": "Matar Kosha (Peas)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 120,
      "unit": "kg",
      "description": "Sweet and tender local green peas.",
      "longDescription": "Freshly shelled or in pod, these winter peas are a seasonal favorite in the Kathmandu valley.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329858.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329858.png",
      "farmName": "Valley Winter Farms",
      "badge": "Seasonal",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Ghiu Simi (French Beans)",
      "name": "Ghiu Simi (French Beans)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 85,
      "unit": "kg",
      "description": "Tender and stringless French beans.",
      "longDescription": "Crispy green beans grown in the mid-hills, perfect for stir-fry or tarkari.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029205.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029205.png",
      "farmName": "Hilly Harvest",
      "badge": "Fresh",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Akabare Khursani (Green Chili)",
      "name": "Akabare Khursani (Green Chili)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 150,
      "unit": "250g",
      "description": "Spicy and aromatic local chilies.",
      "longDescription": "Intensely hot and aromatic chilies from Eastern Nepal. A must-have for spice lovers.",
      "image": "https://cdn-icons-png.flaticon.com/512/1147/1147823.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1147/1147823.png",
      "farmName": "Eastern Spices",
      "badge": "Hot",
      "badgeColor": 0xFFF44336,
    },

    // --- FRUITS ---
    {
      "title": "Mustang Apple",
      "name": "Mustang Apple",
      "category": "Fruits",
      "season": "Autumn",
      "price": 260,
      "unit": "kg",
      "description": "Crispy organic apples from the high Himalayas.",
      "longDescription": "Grown in Marpha, Mustang. These apples are famous for their unique sweetness and crunch due to the mountain climate.",
      "image": "https://cdn-icons-png.flaticon.com/512/415/415733.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/415/415733.png",
      "farmName": "Marpha Himalayan Orchard",
      "badge": "Himalayan",
      "badgeColor": 0xFF7B1FA2,
    },
    {
      "title": "Nepali Suntala (Orange)",
      "name": "Nepali Suntala (Orange)",
      "category": "Fruits",
      "season": "Winter",
      "price": 160,
      "unit": "kg",
      "description": "Juicy and sweet oranges from the hills of Gulmi.",
      "longDescription": "Gulmi oranges are known for their thin skin and high juice content. 100% natural and tree-ripened.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329891.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329891.png",
      "farmName": "Gulmi Citrus Grove",
      "badge": "Sweet",
      "badgeColor": 0xFFFFA000,
    },
    {
      "title": "Terai Malda Mango",
      "name": "Terai Malda Mango",
      "category": "Fruits",
      "season": "Summer",
      "price": 220,
      "unit": "kg",
      "description": "The king of mangoes from Saptari.",
      "longDescription": "Premium Malda mangoes, known for their fiber-less pulp and divine sweetness. Chemical-free ripening.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029227.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029227.png",
      "farmName": "Saptari Tropical Fruit",
      "badge": "Premium",
      "badgeColor": 0xFFFFD600,
    },
    {
      "title": "Local Banana (Kera)",
      "name": "Local Banana (Kera)",
      "category": "Fruits",
      "season": "All Year",
      "price": 120,
      "unit": "dozen",
      "description": "Sweet local 'Malbhog' bananas.",
      "longDescription": "Small but extremely sweet and aromatic local bananas grown in the Terai and mid-hills.",
      "image": "https://cdn-icons-png.flaticon.com/512/415/415737.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/415/415737.png",
      "farmName": "Kavre Banana Farm",
      "badge": "Aromatic",
      "badgeColor": 0xFFFBC02D,
    },
    {
      "title": "Mewabi (Papaya)",
      "name": "Mewabi (Papaya)",
      "category": "Fruits",
      "season": "All Year",
      "price": 90,
      "unit": "kg",
      "description": "Sun-ripened sweet papaya from the plains.",
      "longDescription": "Rich in digestive enzymes and vitamins. Our papayas are naturally ripened on the tree.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029231.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029231.png",
      "farmName": "Chitwan Fruit Estate",
      "badge": "Digestive Aid",
      "badgeColor": 0xFFFFC107,
    },
    {
      "title": "Amala (Gooseberry)",
      "name": "Amala (Gooseberry)",
      "category": "Fruits",
      "season": "Winter",
      "price": 140,
      "unit": "kg",
      "description": "Wild Himalayan gooseberries with high Vitamin C.",
      "longDescription": "Collected from community forests, these gooseberries are powerful immunity boosters used in traditional medicine.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029217.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029217.png",
      "farmName": "Himalayan Herbs",
      "badge": "Immunity",
      "badgeColor": 0xFF009688,
    },
    {
      "title": "Local Grapes (Angur)",
      "name": "Local Grapes (Angur)",
      "category": "Fruits",
      "season": "Summer",
      "price": 350,
      "unit": "kg",
      "description": "Sweet and juicy local green grapes.",
      "longDescription": "Fresh table grapes grown in the foothills of Nepal. Sweet with a slight refreshing tang.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329898.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329898.png",
      "farmName": "Nawalpur Vineyard",
      "badge": "Fresh",
      "badgeColor": 0xFF9C27B0,
    },
    {
      "title": "Bhuikatar (Pineapple)",
      "name": "Bhuikatar (Pineapple)",
      "category": "Fruits",
      "season": "Summer",
      "price": 150,
      "unit": "piece",
      "description": "Tangy and sweet pineapples from the Terai.",
      "longDescription": "Juicy pineapples harvested at peak ripeness. A tropical delight from the gardens of Eastern Nepal.",
      "image": "https://cdn-icons-png.flaticon.com/512/415/415764.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/415/415764.png",
      "farmName": "Eastern Fruit Hub",
      "badge": "Juicy",
      "badgeColor": 0xFFCDDC39,
    },
    {
      "title": "Anar (Pomegranate)",
      "name": "Anar (Pomegranate)",
      "category": "Fruits",
      "season": "All Year",
      "price": 380,
      "unit": "kg",
      "description": "Red and juicy pomegranate seeds.",
      "longDescription": "Highly nutritious pomegranates, known for blood-building properties. Sweet with deep red arils.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029232.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029232.png",
      "farmName": "Salyan Pomegranate Farm",
      "badge": "Healthy",
      "badgeColor": 0xFFE91E63,
    },
    {
      "title": "Amba (Guava)",
      "name": "Amba (Guava)",
      "category": "Fruits",
      "season": "Autumn",
      "price": 80,
      "unit": "kg",
      "description": "Sweet and fragrant local guavas.",
      "longDescription": "White-fleshed local guavas, crunchy and sweet. Harvested directly from the orchards of the mid-hills.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029221.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029221.png",
      "farmName": "Mid-Hill Orchards",
      "badge": "Fragrant",
      "badgeColor": 0xFF4CAF50,
    },

    // --- DAIRY ---
    {
      "title": "Fresh Buffalo Milk",
      "name": "Fresh Buffalo Milk",
      "category": "Dairy",
      "season": "All Year",
      "price": 110,
      "unit": "liter",
      "description": "Pure, unadulterated fresh buffalo milk.",
      "longDescription": "Rich and creamy buffalo milk collected daily from local farmers. No preservatives or chemicals added.",
      "image": "https://cdn-icons-png.flaticon.com/512/372/372971.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/372/372971.png",
      "farmName": "Lalitpur Dairy Farmers",
      "badge": "Pure",
      "badgeColor": 0xFF1976D2,
    },
    {
      "title": "Local Dahi (Curd)",
      "name": "Local Dahi (Curd)",
      "category": "Dairy",
      "season": "All Year",
      "price": 180,
      "unit": "liter",
      "description": "Traditional thick and creamy local curd.",
      "longDescription": "Made from pure buffalo milk using traditional methods. Thick, creamy, and naturally probiotic.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329906.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329906.png",
      "farmName": "Bhaktapur Dairy",
      "badge": "Traditional",
      "badgeColor": 0xFF2196F3,
    },
    {
      "title": "Local Ghiu (Ghee)",
      "name": "Local Ghiu (Ghee)",
      "category": "Dairy",
      "season": "All Year",
      "price": 1400,
      "unit": "kg",
      "description": "Pure hand-churned buffalo ghee.",
      "longDescription": "Traditionally churned using 'Theki-Madan'. Rich aroma and granular texture. Highly nutritious healthy fat.",
      "image": "https://cdn-icons-png.flaticon.com/512/1218/1218698.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1218/1218698.png",
      "farmName": "Village Dairy Coop",
      "badge": "Pure",
      "badgeColor": 0xFFFFC107,
    },
    {
      "title": "Fresh Paneer",
      "name": "Fresh Paneer",
      "category": "Dairy",
      "season": "All Year",
      "price": 850,
      "unit": "kg",
      "description": "Soft and fresh buffalo milk cottage cheese.",
      "longDescription": "Made daily from fresh whole milk. Soft, spongy, and perfect for all your gourmet recipes.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029252.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029252.png",
      "farmName": "Valley Dairy",
      "badge": "High Protein",
      "badgeColor": 0xFF3F51B5,
    },
    {
      "title": "Nauyani (Fresh Butter)",
      "name": "Nauyani (Fresh Butter)",
      "category": "Dairy",
      "season": "All Year",
      "price": 1100,
      "unit": "kg",
      "description": "Traditional white butter from buffalo milk.",
      "longDescription": "Pure and fresh white butter, hand-churned in the village. Perfect for spreading on warm rotis.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029248.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029248.png",
      "farmName": "Hillside Dairy",
      "badge": "Handmade",
      "badgeColor": 0xFF8D6E63,
    },

    // --- GRAINS ---
    {
      "title": "Jumli Marshi Rice",
      "name": "Jumli Marshi Rice",
      "category": "Grains",
      "season": "All Year",
      "price": 320,
      "unit": "kg",
      "description": "Indigenous red rice from high-altitude Jumla.",
      "longDescription": "Cold-resistant indigenous red rice. Extremely nutritious and prized for its unique flavor and health benefits.",
      "image": "https://cdn-icons-png.flaticon.com/512/1000/1000145.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/1000/1000145.png",
      "farmName": "Karnali Highland Grains",
      "badge": "Superfood",
      "badgeColor": 0xFF8D6E63,
    },
    {
      "title": "Local Kodo (Millet)",
      "name": "Local Kodo (Millet)",
      "category": "Grains",
      "season": "All Year",
      "price": 110,
      "unit": "kg",
      "description": "Stone-ground nutritious finger millet.",
      "longDescription": "High-fiber millet from the hills of Kavre. Essential for making traditional and healthy 'Dhido'.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029272.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029272.png",
      "farmName": "Kavre Hill Farming",
      "badge": "Healthy",
      "badgeColor": 0xFF6D4C41,
    },
    {
      "title": "Local Gahun (Wheat)",
      "name": "Local Gahun (Wheat)",
      "category": "Grains",
      "season": "All Year",
      "price": 95,
      "unit": "kg",
      "description": "Whole wheat grains from local fields.",
      "longDescription": "Stone-milled wheat grains, rich in bran and nutrients. Perfect for traditional rotis.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329918.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329918.png",
      "farmName": "Terai Wheat Belt",
      "badge": "Whole Grain",
      "badgeColor": 0xFFF44336,
    },
    {
      "title": "Local Makai (Maize)",
      "name": "Local Makai (Maize)",
      "category": "Grains",
      "season": "All Year",
      "price": 85,
      "unit": "kg",
      "description": "Sun-dried local yellow maize.",
      "longDescription": "Traditionally grown yellow corn, perfect for popping or making cornmeal (Chamre).",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329915.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329915.png",
      "farmName": "Hillside Corn Farms",
      "badge": "Natural",
      "badgeColor": 0xFFFFEB3B,
    },
    {
      "title": "Nepali Quinoa",
      "name": "Nepali Quinoa",
      "category": "Grains",
      "season": "All Year",
      "price": 450,
      "unit": "kg",
      "description": "Locally grown high-protein quinoa.",
      "longDescription": "A modern addition to Nepali agriculture, quinoa is a complete protein source grown in the mountains.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029279.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029279.png",
      "farmName": "Mustang Supergrains",
      "badge": "Protein Rich",
      "badgeColor": 0xFF009688,
    },
    {
      "title": "Makai (Sweet Corn)",
      "name": "Makai (Sweet Corn)",
      "category": "Grains",
      "season": "Summer",
      "price": 60,
      "unit": "piece",
      "description": "Sweet and tender American corn grown locally.",
      "longDescription": "Juicy and sweet yellow corn, perfect for roasting or boiling during the summer monsoon.",
      "image": "https://cdn-icons-png.flaticon.com/512/415/415758.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/415/415758.png",
      "farmName": "Valley Corn Hub",
      "badge": "Sweet",
      "badgeColor": 0xFFFFC107,
    },

    // --- PULSES & SPICES ---
    {
      "title": "Bhatmas (Soybean)",
      "name": "Bhatmas (Soybean)",
      "category": "Pulses",
      "season": "All Year",
      "price": 180,
      "unit": "kg",
      "description": "High-protein local soybeans.",
      "longDescription": "Yellow soybeans from the mid-hills. Perfect for roasting and making 'Bhatmas Sadeko'.",
      "image": "https://cdn-icons-png.flaticon.com/512/5029/5029288.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/5029/5029288.png",
      "farmName": "Local Pulse Coop",
      "badge": "Protein",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Beshar (Turmeric)",
      "name": "Beshar (Turmeric)",
      "category": "Spices",
      "season": "All Year",
      "price": 180,
      "unit": "250g",
      "description": "Pure organic turmeric powder from Salyan.",
      "longDescription": "Grown in the fertile soil of Salyan, this turmeric has exceptionally high curcumin content and deep color.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329860.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329860.png",
      "farmName": "Salyan Organic Village",
      "badge": "High Curcumin",
      "badgeColor": 0xFFFF6F00,
    },
    {
      "title": "Himalayan Honey",
      "name": "Himalayan Honey",
      "category": "Specialty",
      "season": "All Year",
      "price": 1200,
      "unit": "kg",
      "description": "Raw, wild honey from the cliffs of Mustang.",
      "longDescription": "Raw and unprocessed honey collected by honey hunters. Rich in medicinal properties and distinct mountain floral notes.",
      "image": "https://cdn-icons-png.flaticon.com/512/2329/2329924.png",
      "imageUrl": "https://cdn-icons-png.flaticon.com/512/2329/2329924.png",
      "farmName": "Mustang Bee Hunters",
      "badge": "Wild Raw",
      "badgeColor": 0xFFFBC02D,
    },
  ];
