import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';

/// Seeds the database with Nepal products and categories.
/// Returns a map with success and error counts.
Future<Map<String, int>> seedProducts({List<String>? selectedCategories, List<String>? selectedSeasons}) async {
  int productSuccess = 0;
  int productError = 0;
  int categorySuccess = 0;
  int categoryError = 0;

  debugPrint("Starting database seeding process...");

  // Check for authentication
  final User? user = FirebaseAuth.instance.currentUser;
  if (user == null) {
    debugPrint("Seeding Failed: No authenticated user found.");
    throw Exception("Authentication required. Please sign in again.");
  }
  debugPrint("Authenticated as: ${user.email} (UID: ${user.uid})");

  final List<Map<String, dynamic>> nepalProducts = [
    // --- VEGETABLES ---
    {
      "title": "Amaranth (Latte Saag)",
      "name": "Amaranth (Latte Saag)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 40,
      "unit": "bundle",
      "description": "Nutritious leafy green popular in Nepal.",
      "longDescription": "Amaranth leaves, known locally as Latte Saag, are highly nutritious and rich in vitamins and minerals.",
      "imageUrl": "https://images.unsplash.com/photo-1594968973184-2228a009965f?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Himalayan Organic Farms",
      "badge": "Organic",
      "badgeColor": 0xFF2E7D32,
    },
    {
      "title": "Bamboo Shoots (Taama)",
      "name": "Bamboo Shoots (Taama)",
      "category": "Vegetables",
      "season": "Monsoon",
      "price": 120,
      "unit": "500g",
      "description": "Fermented bamboo shoots for traditional curry.",
      "longDescription": "Traditionally fermented bamboo shoots used in the classic 'Aloo Tama' curry. A staple in Nepali cuisine.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Dhading Agri Hub",
      "badge": "Traditional",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Beetroot (Chukander)",
      "name": "Beetroot (Chukander)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 80,
      "unit": "kg",
      "description": "Fresh, earthy beetroots from the valley.",
      "longDescription": "Vibrant red beetroots, perfect for salads and juices. Grown in the loose soil of the Kathmandu valley.",
      "imageUrl": "https://images.unsplash.com/photo-1585944672394-4c9979776d23?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Valley Green Farms",
      "badge": "Fresh",
      "badgeColor": 0xFFD32F2F,
    },
    {
      "title": "Bitter Gourd (Tite Karela)",
      "name": "Bitter Gourd (Tite Karela)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 70,
      "unit": "kg",
      "description": "Organic bitter gourd with medicinal properties.",
      "longDescription": "Green bitter gourd, known for controlling blood sugar and high in nutrients. Best enjoyed fried or in gravy.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Terai Greens",
      "badge": "Healthy",
      "badgeColor": 0xFF388E3C,
    },
    {
      "title": "Bottle Gourd (Lauka)",
      "name": "Bottle Gourd (Lauka)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 50,
      "unit": "kg",
      "description": "Fresh and light bottle gourd.",
      "longDescription": "Hydrating and easy to digest. A perfect summer vegetable for light curries.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Saptari Organic Farm",
      "badge": "Fresh",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Broccoli",
      "name": "Broccoli",
      "category": "Vegetables",
      "season": "Winter",
      "price": 120,
      "unit": "kg",
      "description": "Premium quality green broccoli.",
      "longDescription": "Freshly harvested broccoli, rich in antioxidants and vitamins. Grown in local polytunnels.",
      "imageUrl": "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Bungamati Farmers",
      "badge": "Premium",
      "badgeColor": 0xFF1976D2,
    },
    {
      "title": "Cabbage (Banda Gobi)",
      "name": "Cabbage (Banda Gobi)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 40,
      "unit": "kg",
      "description": "Fresh and compact green cabbage.",
      "longDescription": "Directly from the farm, these cabbages are sweet and packed with nutrients. Great for stir-fry and momo fillings.",
      "imageUrl": "https://images.unsplash.com/photo-1591431759433-02324d862f59?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Lalitpur Agro Farm",
      "badge": "Eco-Friendly",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Carrot (Gajar)",
      "name": "Carrot (Gajar)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 60,
      "unit": "kg",
      "description": "Sweet and crunchy organic carrots.",
      "longDescription": "Grown in the fertile soil of the valley, these carrots are sweet and perfect for salads or halwa.",
      "imageUrl": "https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Green Valley Organic",
      "badge": "Organic",
      "badgeColor": 0xFFFF5722,
    },
    {
      "title": "Cauliflower (Kauli)",
      "name": "Cauliflower (Kauli)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 70,
      "unit": "kg",
      "description": "Crispy white cauliflower from Palung.",
      "longDescription": "Famous for its high-altitude cauliflower. These are sweeter and crunchier than plain varieties.",
      "imageUrl": "https://images.unsplash.com/photo-1568584711075-3d021a7c3ec3?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Mountain Fresh Palung",
      "badge": "Seasonal",
      "badgeColor": 0xFF1976D2,
    },
    {
      "title": "Chayote (Iskus)",
      "name": "Chayote (Iskus)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 30,
      "unit": "kg",
      "description": "Fresh green Iskus from the hills.",
      "longDescription": "A versatile vegetable found across Nepal. High in water content and mild in flavor.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Hilly Harvest",
      "badge": "Fresh",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Cucumber (Kaakro)",
      "name": "Cucumber (Kaakro)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 60,
      "unit": "kg",
      "description": "Hydrating local cucumbers from Bhaktapur.",
      "longDescription": "Crispy and refreshing cucumbers. Perfect for summer salads and traditional Nepali pickles.",
      "imageUrl": "https://images.unsplash.com/photo-1449333254728-79e4ad2b9977?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Bhaktapur Vegetable Group",
      "badge": "Hydrating",
      "badgeColor": 0xFF009688,
    },
    {
      "title": "Eggplant (Bhanta)",
      "name": "Eggplant (Bhanta)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 70,
      "unit": "kg",
      "description": "Shiny purple local brinjals.",
      "longDescription": "Tender and meaty eggplants, ideal for roasting or making traditional 'Bhanta ko Achar'.",
      "imageUrl": "https://images.unsplash.com/photo-1528137850689-d50d52f3692c?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Parsa Agri Farms",
      "badge": "Fresh",
      "badgeColor": 0xFF673AB7,
    },
    {
      "title": "Fiddlehead Fern (Niuro)",
      "name": "Fiddlehead Fern (Niuro)",
      "category": "Vegetables",
      "season": "Monsoon",
      "price": 100,
      "unit": "bundle",
      "description": "Wild, nutritious Himalayan fern.",
      "longDescription": "Freshly foraged Niuro from the hills. A unique seasonal delicacy in Nepal.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Mountain Wild Harvest",
      "badge": "Wild",
      "badgeColor": 0xFF388E3C,
    },
    {
      "title": "Garlic (Lashun)",
      "name": "Garlic (Lashun)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 400,
      "unit": "kg",
      "description": "Strongly flavored local Nepali garlic.",
      "longDescription": "Small-cloved but intensely flavored garlic grown in the mid-hills. Superior in medicinal value.",
      "imageUrl": "https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Hillside Spice Coop",
      "badge": "Intense",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Ginger (Aduwa)",
      "name": "Ginger (Aduwa)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 150,
      "unit": "kg",
      "description": "Organic fresh ginger from Palpa.",
      "longDescription": "High-quality fresh ginger roots, known for their strong aroma. Essential for Nepali tea.",
      "imageUrl": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Palpa Ginger Hub",
      "badge": "Organic",
      "badgeColor": 0xFF2E7D32,
    },
    {
      "title": "Green Beans (Simi)",
      "name": "Green Beans (Simi)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 80,
      "unit": "kg",
      "description": "Tender and stringless French beans.",
      "longDescription": "Crispy green beans grown in the mid-hills, perfect for stir-fry or tarkari.",
      "imageUrl": "https://images.unsplash.com/photo-1567375639018-09558f68297a?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Hilly Harvest",
      "badge": "Fresh",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Kohlrabi (Gyanth Gobi)",
      "name": "Kohlrabi (Gyanth Gobi)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 50,
      "unit": "kg",
      "description": "Fresh and crunchy Kohlrabi.",
      "longDescription": "A crunchy, mild-flavored vegetable. Great for salads or traditional Nepali curries.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Valley Veggie Coop",
      "badge": "Fresh",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Leaf Mustard (Rayo ko Saag)",
      "name": "Leaf Mustard (Rayo ko Saag)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 45,
      "unit": "bundle",
      "description": "Broad leaf mustard from Bhaktapur.",
      "longDescription": "Freshly harvested Rayo ko Saag. Known for its distinct sharp flavor and high Vitamin A.",
      "imageUrl": "https://images.unsplash.com/photo-1594968973184-2228a009965f?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Bhaktapur Organic Farm",
      "badge": "Local",
      "badgeColor": 0xFF2E7D32,
    },
    {
      "title": "Okra (Ramtoriya)",
      "name": "Okra (Ramtoriya)",
      "category": "Vegetables",
      "season": "Summer",
      "price": 90,
      "unit": "kg",
      "description": "Tender green lady fingers.",
      "longDescription": "Freshly picked okra, rich in fiber. Best enjoyed as a crispy fry or in gravy.",
      "imageUrl": "https://images.unsplash.com/photo-1567375639018-09558f68297a?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Chitwan Agri Hub",
      "badge": "Tender",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Onion (Pyaj)",
      "name": "Onion (Pyaj)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 80,
      "unit": "kg",
      "description": "Organic onions from local farms.",
      "longDescription": "Essential ingredient for every Nepali dish. Our onions are grown naturally.",
      "imageUrl": "https://images.unsplash.com/photo-1508747703725-71977713d540?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Terai Harvest",
      "badge": "Pungent",
      "badgeColor": 0xFFE64A19,
    },
    {
      "title": "Potato (Alu)",
      "name": "Potato (Alu)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 70,
      "unit": "kg",
      "description": "Organic potatoes from the valley.",
      "longDescription": "Versatile and essential. Grown without heavy pesticides.",
      "imageUrl": "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Kathmandu Agri Coop",
      "badge": "Daily Staple",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Pumpkin (Pharsi)",
      "name": "Pumpkin (Pharsi)",
      "category": "Vegetables",
      "season": "Autumn",
      "price": 45,
      "unit": "kg",
      "description": "Sweet local pumpkin from the plains.",
      "longDescription": "Large, ripe pumpkins from the Terai. Perfect for soups and curries.",
      "imageUrl": "https://images.unsplash.com/photo-1506815444479-bfdb1e96c566?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Terai Harvest",
      "badge": "Sweet",
      "badgeColor": 0xFFFF9800,
    },
    {
      "title": "Radish (Mula)",
      "name": "Radish (Mula)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 30,
      "unit": "kg",
      "description": "Crispy white radish for pickles.",
      "longDescription": "Fresh winter radish, perfect for traditional sun-dried 'Sinki' or spicy pickles.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Bhaktapur Roots",
      "badge": "Crunchy",
      "badgeColor": 0xFF00BCD4,
    },
    {
      "title": "Spinach (Paalungo)",
      "name": "Spinach (Paalungo)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 50,
      "unit": "bundle",
      "description": "Iron-rich fresh spinach leaves.",
      "longDescription": "Freshly harvested organic spinach from the valley. Packed with essential vitamins.",
      "imageUrl": "https://images.unsplash.com/photo-1594968973184-2228a009965f?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Valley Greens",
      "badge": "Superfood",
      "badgeColor": 0xFF43A047,
    },
    {
      "title": "Sweet Potato (Sakhar Khand)",
      "name": "Sweet Potato (Sakhar Khand)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 80,
      "unit": "kg",
      "description": "Organic sweet potatoes from the plains.",
      "longDescription": "Sweet and nutritious tubers, traditionally eaten during Maghe Sankranti.",
      "imageUrl": "https://images.unsplash.com/photo-1596097561442-6be441194565?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Terai Sweet Harvest",
      "badge": "Nutritious",
      "badgeColor": 0xFFF57C00,
    },
    {
      "title": "Tamarind (Imli)",
      "name": "Tamarind (Imli)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 200,
      "unit": "kg",
      "description": "Tangy local tamarind.",
      "longDescription": "Sour and tangy, used for making chutneys and adding flavor to curries.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Eastern Spices",
      "badge": "Tangy",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Taro (Pidaalu)",
      "name": "Taro (Pidaalu)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 60,
      "unit": "kg",
      "description": "Traditional taro roots from the mid-hills.",
      "longDescription": "Meaty and flavorful roots, a winter staple in many Nepali households.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Hillside Roots",
      "badge": "Traditional",
      "badgeColor": 0xFF8D6E63,
    },
    {
      "title": "Tomato (Golebheda)",
      "name": "Tomato (Golebheda)",
      "category": "Vegetables",
      "season": "All Year",
      "price": 60,
      "unit": "kg",
      "description": "Fresh, vine-ripened organic tomatoes.",
      "longDescription": "Juicy and plump tomatoes grown locally. Perfect for salads and chutneys.",
      "imageUrl": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Kathmandu Valley Green Farms",
      "badge": "Fresh",
      "badgeColor": 0xFFD32F2F,
    },
    {
      "title": "Turnip (Salgam)",
      "name": "Turnip (Salgam)",
      "category": "Vegetables",
      "season": "Winter",
      "price": 50,
      "unit": "kg",
      "description": "Crispy white turnips from the valley.",
      "longDescription": "Fresh turnips, perfect for pickling or adding to traditional meat stews.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Lalitpur Agro Farm",
      "badge": "Fresh",
      "badgeColor": 0xFF8BC34A,
    },

    // --- FRUITS ---
    {
      "title": "Apple (Syau)",
      "name": "Apple (Syau)",
      "category": "Fruits",
      "season": "Autumn",
      "price": 260,
      "unit": "kg",
      "description": "Crispy organic apples from Mustang.",
      "longDescription": "Grown in Marpha, Mustang. These apples are famous for their unique sweetness.",
      "imageUrl": "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Marpha Himalayan Orchard",
      "badge": "Himalayan",
      "badgeColor": 0xFF7B1FA2,
    },
    {
      "title": "Apricot (Khurpaani)",
      "name": "Apricot (Khurpaani)",
      "category": "Fruits",
      "season": "Summer",
      "price": 350,
      "unit": "kg",
      "description": "Organic Himalayan apricots.",
      "longDescription": "Sweet and aromatic apricots from the high-altitude orchards of Mustang.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Mustang Fruit Estate",
      "badge": "High Altitude",
      "badgeColor": 0xFFFFB300,
    },
    {
      "title": "Banana (Kera)",
      "name": "Banana (Kera)",
      "category": "Fruits",
      "season": "All Year",
      "price": 120,
      "unit": "dozen",
      "description": "Sweet local 'Malbhog' bananas.",
      "longDescription": "Small but extremely sweet and aromatic local bananas grown in the Terai.",
      "imageUrl": "https://images.unsplash.com/photo-1603833665858-e61d17a86224?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Kavre Banana Farm",
      "badge": "Aromatic",
      "badgeColor": 0xFFFBC02D,
    },
    {
      "title": "Bayberry (Kafal)",
      "name": "Bayberry (Kafal)",
      "category": "Fruits",
      "season": "Spring",
      "price": 200,
      "unit": "kg",
      "description": "Wild, tangy Himalayan bayberries.",
      "longDescription": "Seasonal wild fruit from the forests of Nepal. Tangy and refreshing.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Forest Harvest",
      "badge": "Wild",
      "badgeColor": 0xFF9C27B0,
    },
    {
      "title": "Custard Apple (Sariphaa)",
      "name": "Custard Apple (Sariphaa)",
      "category": "Fruits",
      "season": "Autumn",
      "price": 150,
      "unit": "kg",
      "description": "Creamy and sweet local custard apples.",
      "longDescription": "Grown in the mid-hills, these fruits have a creamy texture and sweet flavor.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Mid-Hill Orchards",
      "badge": "Creamy",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Guava (Amba)",
      "name": "Guava (Amba)",
      "category": "Fruits",
      "season": "Autumn",
      "price": 80,
      "unit": "kg",
      "description": "Sweet and fragrant local guavas.",
      "longDescription": "White-fleshed local guavas, crunchy and sweet. Harvested directly from the orchards.",
      "imageUrl": "https://images.unsplash.com/photo-1534073828943-f801091bb18c?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Valley Orchards",
      "badge": "Fragrant",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Hog Plum (Lapsi)",
      "name": "Hog Plum (Lapsi)",
      "category": "Fruits",
      "season": "Winter",
      "price": 60,
      "unit": "kg",
      "description": "Sour hog plums perfect for pickles.",
      "longDescription": "Unique to Nepal, Lapsi is used for making candies and pickles. High in Vitamin C.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Kathmandu Valley Orchards",
      "badge": "Local Choice",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Indian Gooseberry (Amala)",
      "name": "Indian Gooseberry (Amala)",
      "category": "Fruits",
      "season": "Winter",
      "price": 140,
      "unit": "kg",
      "description": "Wild Himalayan gooseberries.",
      "longDescription": "Powerhouse of Vitamin C. Great for immunity and digestion.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Himalayan Herbs",
      "badge": "Immunity",
      "badgeColor": 0xFF009688,
    },
    {
      "title": "Jackfruit (Rukh Katahar)",
      "name": "Jackfruit (Rukh Katahar)",
      "category": "Fruits",
      "season": "Summer",
      "price": 100,
      "unit": "kg",
      "description": "Large, sweet jackfruit from the Terai.",
      "longDescription": "Sweet and aromatic jackfruit. Can be eaten as a fruit or used as a vegetable when unripe.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Chitwan Fruit Estate",
      "badge": "Large",
      "badgeColor": 0xFFFFB300,
    },
    {
      "title": "Lemon/Lime (Kaagati)",
      "name": "Lemon/Lime (Kaagati)",
      "category": "Fruits",
      "season": "All Year",
      "price": 150,
      "unit": "kg",
      "description": "Fresh and tangy local lemons.",
      "longDescription": "Essential for refreshments and adding zest to food. Grown across the Terai.",
      "imageUrl": "https://images.unsplash.com/photo-1590502593452-192070f3f232?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Nawalpur Citrus",
      "badge": "Tangy",
      "badgeColor": 0xFFCDDC39,
    },
    {
      "title": "Lychee (Lichi)",
      "name": "Lychee (Lichi)",
      "category": "Fruits",
      "season": "Summer",
      "price": 250,
      "unit": "kg",
      "description": "Juicy and sweet lychees from Terai.",
      "longDescription": "Seasonal summer delight from the Terai orchards. Sweet, juicy, and aromatic.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Rautahat Fruit Belt",
      "badge": "Juicy",
      "badgeColor": 0xFFE91E63,
    },
    {
      "title": "Mandarin/Orange (Suntala)",
      "name": "Mandarin/Orange (Suntala)",
      "category": "Fruits",
      "season": "Winter",
      "price": 160,
      "unit": "kg",
      "description": "Juicy oranges from the hills of Gulmi.",
      "longDescription": "Gulmi oranges are thin-skinned and packed with juice. 100% natural and tree-ripened.",
      "imageUrl": "https://images.unsplash.com/photo-1611080626919-7cf5a9caab53?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Gulmi Citrus Grove",
      "badge": "Sweet",
      "badgeColor": 0xFFFFA000,
    },
    {
      "title": "Mango (Aanp)",
      "name": "Mango (Aanp)",
      "category": "Fruits",
      "season": "Summer",
      "price": 220,
      "unit": "kg",
      "description": "The king of mangoes from Saptari.",
      "longDescription": "Premium Malda mangoes, known for their fiber-less pulp and divine sweetness.",
      "imageUrl": "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Saptari Tropical Fruit",
      "badge": "Premium",
      "badgeColor": 0xFFFFD600,
    },
    {
      "title": "Mulberry (Kimbu)",
      "name": "Mulberry (Kimbu)",
      "category": "Fruits",
      "season": "Spring",
      "price": 180,
      "unit": "kg",
      "description": "Sweet and juicy local mulberries.",
      "longDescription": "Freshly picked mulberries from the mid-hills. Rich in vitamins.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Mid-Hill Berries",
      "badge": "Fresh",
      "badgeColor": 0xFF9C27B0,
    },
    {
      "title": "Papaya (Mewaa)",
      "name": "Papaya (Mewaa)",
      "category": "Fruits",
      "season": "All Year",
      "price": 90,
      "unit": "kg",
      "description": "Sun-ripened sweet papaya from the plains.",
      "longDescription": "Naturally ripened on the tree. Rich in digestive enzymes and vitamins.",
      "imageUrl": "https://images.unsplash.com/photo-1517282003755-6b3531649987?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Chitwan Fruit Estate",
      "badge": "Healthy",
      "badgeColor": 0xFFFFC107,
    },
    {
      "title": "Peach (Aaru)",
      "name": "Peach (Aaru)",
      "category": "Fruits",
      "season": "Summer",
      "price": 180,
      "unit": "kg",
      "description": "Juicy and aromatic local peaches.",
      "longDescription": "Grown in the valley, these peaches are sweet with a soft velvety skin.",
      "imageUrl": "https://images.unsplash.com/photo-1521404113591-2bc8a02a829e?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Kathmandu Orchards",
      "badge": "Juicy",
      "badgeColor": 0xFFFF8A65,
    },
    {
      "title": "Pear (Nashpaati)",
      "name": "Pear (Nashpaati)",
      "category": "Fruits",
      "season": "Summer",
      "price": 120,
      "unit": "kg",
      "description": "Crispy local pears from the valley.",
      "longDescription": "Sweet and crunchy local pears. A favorite seasonal fruit in Kathmandu.",
      "imageUrl": "https://images.unsplash.com/photo-1514756331096-242f390effee?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Valley Fruit Group",
      "badge": "Crunchy",
      "badgeColor": 0xFF8BC34A,
    },
    {
      "title": "Persimmon (Haluwaabed)",
      "name": "Persimmon (Haluwaabed)",
      "category": "Fruits",
      "season": "Autumn",
      "price": 200,
      "unit": "kg",
      "description": "Sweet and soft local persimmons.",
      "longDescription": "Known locally as Haluwaabed, these fruits have a unique custard-like texture.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Mid-Hill Harvest",
      "badge": "Sweet",
      "badgeColor": 0xFFFFB300,
    },
    {
      "title": "Pineapple (Bhuin Katahar)",
      "name": "Pineapple (Bhuin Katahar)",
      "category": "Fruits",
      "season": "Summer",
      "price": 150,
      "unit": "piece",
      "description": "Tangy and sweet pineapples from Terai.",
      "longDescription": "Juicy pineapples harvested at peak ripeness from the Terai gardens.",
      "imageUrl": "https://images.unsplash.com/photo-1550258114-68bd2950599d?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Eastern Fruit Hub",
      "badge": "Juicy",
      "badgeColor": 0xFFCDDC39,
    },
    {
      "title": "Plum (Alubukhara)",
      "name": "Plum (Alubukhara)",
      "category": "Fruits",
      "season": "Summer",
      "price": 160,
      "unit": "kg",
      "description": "Sweet and tangy local plums.",
      "longDescription": "Vibrant and juicy plums from the mid-hills. Perfect for fresh eating or jams.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Hillside Orchards",
      "badge": "Fresh",
      "badgeColor": 0xFF9C27B0,
    },
    {
      "title": "Pomegranate (Anaar)",
      "name": "Pomegranate (Anaar)",
      "category": "Fruits",
      "season": "All Year",
      "price": 380,
      "unit": "kg",
      "description": "Red and juicy pomegranate seeds.",
      "longDescription": "Highly nutritious pomegranates, known for blood-building properties.",
      "imageUrl": "https://images.unsplash.com/photo-1604177042704-338871638f21?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Salyan Fruit Farm",
      "badge": "Healthy",
      "badgeColor": 0xFFE91E63,
    },
    {
      "title": "Pomelo (Bhogate)",
      "name": "Pomelo (Bhogate)",
      "category": "Fruits",
      "season": "Autumn",
      "price": 100,
      "unit": "piece",
      "description": "Large, citrusy local pomelos.",
      "longDescription": "Known as Bhogate, often enjoyed in the sun with spices and salt.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Valley Citrus Farm",
      "badge": "Large",
      "badgeColor": 0xFFCDDC39,
    },
    {
      "title": "Watermelon (Kharbuja)",
      "name": "Watermelon (Kharbuja)",
      "category": "Fruits",
      "season": "Summer",
      "price": 60,
      "unit": "kg",
      "description": "Sweet and juicy local watermelon.",
      "longDescription": "Perfect summer refresher from the sandy riverbeds of the Terai.",
      "imageUrl": "https://images.unsplash.com/photo-1587049352861-81004ccfb8c2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Nawalparasi Agri Group",
      "badge": "Summer Special",
      "badgeColor": 0xFFE91E63,
    },

    // --- SPICES (Masala) ---
    {
      "title": "Asafoetida (Hing)",
      "name": "Asafoetida (Hing)",
      "category": "Spices",
      "season": "All Year",
      "price": 150,
      "unit": "50g",
      "description": "Strongly aromatic Hing for tempering.",
      "longDescription": "High-quality Asafoetida, essential for tempering dal and vegetables in Nepali cooking.",
      "imageUrl": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Himalayan Spice Collective",
      "badge": "Aromatic",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Black Cardamom (Alaichi)",
      "name": "Black Cardamom (Alaichi)",
      "category": "Spices",
      "season": "All Year",
      "price": 250,
      "unit": "100g",
      "description": "Smoky and aromatic black cardamom.",
      "longDescription": "Grown in Eastern Nepal, these pods are famous for their smoky flavor and medicinal value.",
      "imageUrl": "https://images.unsplash.com/photo-1510627489930-0c1b0ba80086?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Ilam Spice Hub",
      "badge": "Smoky",
      "badgeColor": 0xFF3E2723,
    },
    {
      "title": "Black Pepper (Marich)",
      "name": "Black Pepper (Marich)",
      "category": "Spices",
      "season": "All Year",
      "price": 180,
      "unit": "100g",
      "description": "Pure black pepper corns.",
      "longDescription": "Spicy and pungent black pepper corns from the Terai regions.",
      "imageUrl": "https://images.unsplash.com/photo-1532336414038-cf19250c5757?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Surkhet Spice Mill",
      "badge": "Pure",
      "badgeColor": 0xFF212121,
    },
    {
      "title": "Carom Seeds (Jwano)",
      "name": "Carom Seeds (Jwano)",
      "category": "Spices",
      "season": "All Year",
      "price": 60,
      "unit": "100g",
      "description": "Medicinal carom seeds.",
      "longDescription": "Commonly used for postpartum care and as a medicinal spice in Nepal.",
      "imageUrl": "https://images.unsplash.com/photo-1599590984817-0314752674e2?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Local Herb Collective",
      "badge": "Medicinal",
      "badgeColor": 0xFF388E3C,
    },
    {
      "title": "Cinnamon (Dalchini)",
      "name": "Cinnamon (Dalchini)",
      "category": "Spices",
      "season": "All Year",
      "price": 120,
      "unit": "100g",
      "description": "Fragrant cinnamon bark.",
      "longDescription": "Sweet and spicy cinnamon bark, essential for masala tea and curries.",
      "imageUrl": "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Tropical Spice Farm",
      "badge": "Fragrant",
      "badgeColor": 0xFF8D6E63,
    },
    {
      "title": "Clove (Lwang)",
      "name": "Clove (Lwang)",
      "category": "Spices",
      "season": "All Year",
      "price": 300,
      "unit": "50g",
      "description": "High-quality whole cloves.",
      "longDescription": "Aromatic cloves with high oil content. Great for cooking and dental care.",
      "imageUrl": "https://images.unsplash.com/photo-1595123550441-d377e017de6a?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Surkhet Spice Mill",
      "badge": "Intense",
      "badgeColor": 0xFF3E2723,
    },
    {
      "title": "Coriander Seeds (Dhaniya)",
      "name": "Coriander Seeds (Dhaniya)",
      "category": "Spices",
      "season": "All Year",
      "price": 80,
      "unit": "200g",
      "description": "Organic coriander seeds.",
      "longDescription": "Fresh and aromatic seeds, essential for making local spice mixes.",
      "imageUrl": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Valley Spice Coop",
      "badge": "Aromatic",
      "badgeColor": 0xFF4CAF50,
    },
    {
      "title": "Cumin Seeds (Jeera)",
      "name": "Cumin Seeds (Jeera)",
      "category": "Spices",
      "season": "All Year",
      "price": 150,
      "unit": "200g",
      "description": "High-quality cumin seeds.",
      "longDescription": "Earthy and aromatic seeds, the foundation of Nepali masalas.",
      "imageUrl": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Terai Spice Hub",
      "badge": "Earthy",
      "badgeColor": 0xFF795548,
    },
    {
      "title": "Fenugreek Seeds (Methi)",
      "name": "Fenugreek Seeds (Methi)",
      "category": "Spices",
      "season": "All Year",
      "price": 70,
      "unit": "100g",
      "description": "Aromatic fenugreek seeds.",
      "longDescription": "Used for tempering, adding a unique slightly bitter flavor to curries.",
      "imageUrl": "https://images.unsplash.com/photo-1589135339683-17639c7f9995?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Local Garden Coop",
      "badge": "Pure",
      "badgeColor": 0xFFFFB300,
    },
    {
      "title": "Mustard Seeds (Tori)",
      "name": "Mustard Seeds (Tori)",
      "category": "Spices",
      "season": "All Year",
      "price": 90,
      "unit": "500g",
      "description": "Organic yellow mustard seeds.",
      "longDescription": "Grown in the mid-hills, used for oil extraction and pickling.",
      "imageUrl": "https://images.unsplash.com/photo-1615485240318-10f4889b9ba1?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Terai Harvest",
      "badge": "Pure",
      "badgeColor": 0xFFFFC107,
    },
    {
      "title": "Nutmeg (Jaiphal)",
      "name": "Nutmeg (Jaiphal)",
      "category": "Spices",
      "season": "All Year",
      "price": 100,
      "unit": "piece",
      "description": "Aromatic whole nutmeg.",
      "longDescription": "Sweet and warm spice used sparingly in traditional Nepali sweets and masalas.",
      "imageUrl": "https://images.unsplash.com/photo-1593390191839-38f45f9429ba?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Highland Spices",
      "badge": "Warm",
      "badgeColor": 0xFF8D6E63,
    },
    {
      "title": "Sichuan Pepper (Timur)",
      "name": "Sichuan Pepper (Timur)",
      "category": "Spices",
      "season": "Autumn",
      "price": 120,
      "unit": "100g",
      "description": "Zesty and numbing Timur from the hills.",
      "longDescription": "Unique to the region, providing a citrusy aroma and numbing sensation.",
      "imageUrl": "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Surkhet Spice Hub",
      "badge": "Unique",
      "badgeColor": 0xFF607D8B,
    },
    {
      "title": "Turmeric (Besar)",
      "name": "Turmeric (Besar)",
      "category": "Spices",
      "season": "All Year",
      "price": 180,
      "unit": "250g",
      "description": "Pure organic turmeric powder from Salyan.",
      "longDescription": "Grown in the fertile soil of Salyan, this turmeric has high curcumin content.",
      "imageUrl": "https://images.unsplash.com/photo-1615485240318-10f4889b9ba1?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Salyan Organic Village",
      "badge": "Pure",
      "badgeColor": 0xFFFF6F00,
    },

    // --- MUSHROOMS (Chau) ---
    {
      "title": "Button Mushroom",
      "name": "Button Mushroom",
      "category": "Mushrooms",
      "season": "All Year",
      "price": 300,
      "unit": "kg",
      "description": "Fresh white button mushrooms.",
      "longDescription": "Grown in controlled environments, these mushrooms are fresh and tender.",
      "imageUrl": "https://images.unsplash.com/photo-1567608285749-c6bb167c9c07?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Valley Mushroom Farm",
      "badge": "Fresh",
      "badgeColor": 0xFF689F38,
    },
    {
      "title": "Oyster Mushroom",
      "name": "Oyster Mushroom",
      "category": "Mushrooms",
      "season": "All Year",
      "price": 250,
      "unit": "kg",
      "description": "Organic oyster mushrooms.",
      "longDescription": "Grown on organic substrate, these mushrooms have a delicate texture and savory flavor.",
      "imageUrl": "https://images.unsplash.com/photo-1612141853201-20bf3682496d?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Kavre Organic Hub",
      "badge": "Organic",
      "badgeColor": 0xFF2E7D32,
    },
    {
      "title": "Shiitake Mushroom",
      "name": "Shiitake Mushroom",
      "category": "Mushrooms",
      "season": "All Year",
      "price": 800,
      "unit": "kg",
      "description": "Premium local Shiitake mushrooms.",
      "longDescription": "Grown on logs in the mid-hills, these mushrooms are rich in flavor and nutrients.",
      "imageUrl": "https://images.unsplash.com/photo-1504675099198-7023dd85f5a3?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Hillside Mushroom Coop",
      "badge": "Premium",
      "badgeColor": 0xFF1976D2,
    },
    {
      "title": "Wild Forest Mushrooms",
      "name": "Wild Forest Mushrooms",
      "category": "Mushrooms",
      "season": "Monsoon",
      "price": 1200,
      "unit": "kg",
      "description": "Rare wild mushrooms from the forests.",
      "longDescription": "Seasonal wild mushrooms foraged from the forests of Nepal. Highly prized for their unique taste.",
      "imageUrl": "https://images.unsplash.com/photo-1504675099198-7023dd85f5a3?auto=format&fit=crop&q=80&w=1000",
      "farmName": "Forest Community Groups",
      "badge": "Wild",
      "badgeColor": 0xFF388E3C,
    },
  ];

  final CollectionReference products = FirebaseFirestore.instance.collection('master_catalog');
  debugPrint("Beginning catalog seeding. Target products: ${nepalProducts.length}");

  for (var product in nepalProducts) {
    bool catMatch = selectedCategories == null || selectedCategories.contains(product['category']);
    bool seasonMatch = selectedSeasons == null || selectedSeasons.contains(product['season']) || product['season'] == 'All Year';

    if (catMatch && seasonMatch) {
      try {
        product['addedAt'] = FieldValue.serverTimestamp();
        product['updatedAt'] = FieldValue.serverTimestamp();
        product['rating'] = 4.8;
        product['image'] = product['imageUrl'];
        
        String docId = product['name'].toString().replaceAll(' ', '_').toLowerCase();
        
        await products.doc(docId).set(product, SetOptions(merge: true)).timeout(
          const Duration(seconds: 10),
          onTimeout: () => throw Exception("Write timeout for ${product['name']}"),
        );
        
        productSuccess++;
        debugPrint("✓ Seeded Product: ${product['name']}");
      } catch (e) {
        productError++;
        debugPrint("✗ Error seeding product ${product['name']}: $e");
      }
    }
  }

  // Categories seed logic
  final List<Map<String, dynamic>> categoriesData = [
    {"name": "Vegetables", "iconCode": Icons.eco_outlined.codePoint},
    {"name": "Fruits", "iconCode": Icons.apple_outlined.codePoint},
    {"name": "Dairy", "iconCode": Icons.local_drink_outlined.codePoint},
    {"name": "Grains", "iconCode": Icons.grain.codePoint},
    {"name": "Tea & Coffee", "iconCode": Icons.local_cafe_outlined.codePoint},
    {"name": "Spices", "iconCode": Icons.flare.codePoint},
    {"name": "Pulses", "iconCode": Icons.lens_blur.codePoint},
    {"name": "Mushrooms", "iconCode": Icons.spa.codePoint},
    {"name": "Specialty", "iconCode": Icons.star_border.codePoint},
  ];

  final CollectionReference categoriesCol = FirebaseFirestore.instance.collection('categories');
  debugPrint("Beginning categories seeding. Target categories: ${categoriesData.length}");

  for (var cat in categoriesData) {
    try {
      if (selectedCategories == null || selectedCategories.contains(cat['name'])) {
        await categoriesCol.doc(cat['name']).set(cat, SetOptions(merge: true)).timeout(
          const Duration(seconds: 10),
          onTimeout: () => throw Exception("Write timeout for category ${cat['name']}"),
        );
        categorySuccess++;
        debugPrint("✓ Seeded Category: ${cat['name']}");
      }
    } catch (e) {
      categoryError++;
      debugPrint("✗ Error seeding category ${cat['name']}: $e");
    }
  }

  debugPrint("Seeding Finished. Products: $productSuccess success / $productError error. Categories: $categorySuccess success / $categoryError error.");
  
  return {
    'productSuccess': productSuccess,
    'productError': productError,
    'categorySuccess': categorySuccess,
    'categoryError': categoryError,
  };
}
